# Generated by Django 5.2.3 on 2025-07-02 17:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.CharField(
                        editable=False,
                        max_length=100,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("username", models.CharField(max_length=150, unique=True)),
                (
                    "plan",
                    models.CharField(
                        choices=[("HOBBY", "Hobby"), ("PRO", "Pro")], max_length=10
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="DeployedApp",
            fields=[
                (
                    "id",
                    models.CharField(
                        editable=False,
                        max_length=100,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("active", models.BooleanField(default=True)),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="apps",
                        to="core.user",
                    ),
                ),
            ],
        ),
    ]
